Functions:
  prj_loss: 
    func: DiceLoss
    args: [10, sum, sqrt]
  obj_loss: 
    func: CrossEntropyLoss
    args: [1, sum, bce_use_sigmoid]
  cls_loss: 
    func: CrossEntropyLoss
    args: [1, sum, bce_use_sigmoid]
  reg_loss:
    func: IoULoss
    args: [5, sum, iou]
  reg_loss_extra:
    func: L1Loss
    args: [1, sum, norm]
Args:
  loss_pairwise_weight: 1.0
  prior_prob: 0.01
  bbox_pre_topk: 3000
  bbox_nms_topk: 100
  bbox_iou_thre: 0.65
  pairwise_warmup: 5000
  pairwise_color_thresh: 0.3
  pairwise_size: 3
  pairwise_dilation: 2




  
  
