Functions:
  obj_loss: 
    func: CrossEntropyLoss
    args: [1, sum, bce_use_sigmoid]
  cls_loss: 
    func: CrossEntropyLoss
    args: [1, sum, bce_use_sigmoid]
  reg_loss:
    func: PolyIoULoss
    args: [5, sum, "linear"]
  reg_loss_extra:
    func: L1Loss
    args: [1, sum, norm]
Args:
  prior_prob: 0.01